version: "3"

services:
  frontend:
    container_name: next-frontend
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    restart: unless-stopped
    env_file: .env.production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_STRAPI_API_URL=${NEXT_PUBLIC_STRAPI_API_URL}
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    container_name: strapi-backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: unless-stopped
    env_file: .env.production
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - APP_KEYS=${APP_KEYS}
      - API_TOKEN_SALT=${API_TOKEN_SALT}
      - TRANSFER_TOKEN_SALT=${TRANSFER_TOKEN_SALT}
    volumes:
      - ./apps/backend/public/uploads:/app/public/uploads
      - strapi-data:/app/apps/backend/.tmp
    ports:
      - "1337:1337"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  strapi-data:
